name: art_display_visuallizer
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  firebase_database: ^3.1.3
  http: ^0.12.0+2
  intl: ^0.16.0
  font_awesome_flutter: ^8.5.0
  google_maps_flutter: ^0.5.21+15
  firebase_core: ^0.4.4+3
  firebase_storage: ^3.1.5
  firebase_analytics: ^5.0.11
  shared_preferences: ^0.4.0
  flutter_redux: ^0.6.0
  redux_logging: ^0.4.0
  image_picker: 0.6.3+4
  path_provider: ^1.6.7
  #provider: ^4.0.5+1
  photo_view: ^0.9.2
  flutter_svg: ^0.17.4
  cached_network_image: ^2.2.0+1
  zoomable_image: ^1.3.1
  cloud_firestore: any
  image_gallery_saver: ^1.2.1
  #image_picker_saver: ^0.3.0
  screenshot: ^0.1.1
  convert: ^2.1.1
  flutter_email_sender: ^3.0.1
  matrix_gesture_detector: ^0.1.0
  #easy_permission_validator: ^2.0.0
  #permission_handler: ^5.0.0
  auto_size_text: ^2.1.0

  firebase_auth: ^0.16.0
  google_sign_in: ^4.4.4
  rxdart: 0.23.1


dev_dependencies:
  flutter_test:
    sdk: flutter




# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/large-image.jpg
    - assets/firefox.svg
    - assets/large-image.jpg
    - assets/small-image.jpg
    - assets/peanut.gif
    - assets/gallery3.jpg
    - assets/gallery2.jpg
    - assets/gallery1.jpg
    - images/google.jpg
    - images/facebook.png
    - images/gmail.ico
    - images/black walls yellow couch.jpg
    - images/blue wall white bed.jpg
    - images/brick kitchen.jpg
    - images/Brick Livingroom.jpg
    - images/Brick Livingroom Brown couch.jpg
    - images/brickkitchen.jpg
    - images/concrete wall.jpg
    - images/concrete wall bedroom.jpg
    - images/concrete wall grey bed.jpg
    - images/Family on couch.jpg
    - images/Green Walls White Couch.jpg
    - images/Grey Couch.jpg
    - images/grey couch green and yellow.jpg
    - images/Grey wall beige chair.jpg
    - images/leather couch.jpg
    - images/Light Blue Bedroom.jpg
    - images/purple.jpg
    - images/small green wall brown couch.jpg
    - images/white everything.jpg
    - images/white wall brown couch.jpg
    - images/white walls greay couch.jpg
    - images/white walls white couch.jpg
    - images/Yellow Walls Red Couch.PNG
    - images/Yellow Walls Yellow Couch.jpg
    - images/geode blue.jpg
    - images/geode flat purple.jpg
    - images/geode gold.jpg
    - images/geode purple.jpg
    - images/geode rose.jpg
    - images/geode teal.jpg
    - images/teal geode.jpg
    - images/geode aura quartz blue and gold.jfif
    - images/blank.png
    - images/Living Room White Couch.png
    - images/Living Room White Leather.jpg
    - images/Living Room All White.jpg
    - images/Living Room White Wall.jpg
    - images/white everything.jpg
    - images/White wall beige couch.jfif
    - images/white walls greay couch.jpg
    - images/Green Walls White Couch.jpg
    - images/Living Room Beige Everything.jpg
    - images/Living Room All Beige.jpg
    - images/Living Room Beige Leather.png
    - images/Living Room Beige.jpg
    - images/Living Room Beige Couch.jpg
    - images/Living Room Beige Wall.jpg
    - images/Living Room Brick Beige Couch.jpg
    - images/Living Room Grey Couch.png
    - images/Living Room Grey Everything.jpg
    - images/Living Room All Grey.jpg
    - images/Living Room Conrete Grey Couch.jpg
    - images/Living Room Dark Grey.jpg
    - images/Living Room Blue Wall.jpg
    - images/Living Room Pink.png
    - images/Living Room Pink Wall.jpg
    - images/Living Room Pink Chair.jpg
    - images/black walls yellow couch.jpg
    - images/Living Room Bamboo.jpg
    - images/Living Room Beach.jpg
    - images/Living Room Brick Brown Couch.jpg
    - images/Living Room Concrete.jpg
    - images/Living Room Fancy.jpg
    - images/Living Room Flowers.jpg
    - images/Living Room Gold.png
    - images/Living Room Green Couch.jpg
    - images/Living Room Greenery.jpg
    - images/Living Room Hotel.jpg
    - images/Living Room Marble.jpg
    - images/Living Room Open.jfif
    - images/Living Room Plain.jpg
    - images/Living Room Red Couch.jpg
    - images/Living Room Retro.jpg
    - images/Living Room Rustic.jpg
    - images/Living Room Wood.jpg
    - images/small green wall brown couch.jpg
    - images/Yellow Walls Red Couch.png
    - images/Yellow Walls Yellow Couch.jpg
    - images/Living Room Brick Wall Yellow Couch.jpeg
    - images/Blue Grey Wall.jpg
    - images/fireplace.jpg
    - images/Resin Geode.jpg
    - images/Transparent Grey Geode.png
    - images/Transparent Purple Geode.png
    - images/dark purple.jpg
    - images/teal crystal.jpg
    - images/pink crystal.png
    - images/Geode Grey.jpg
    - images/crystal.jpg
    - images/teal.png
    - images/purple blue.jpg
    - images/Living Room Yellow.jpg
    - images/Blue Geode.jpg
    - images/egate.png
    - images/light pink agate.png
    - images/light purple agate.png
    - images/pink geode.png
    - images/pink couch flower wallpaper.png
    - images/brown.png
    - images/green agate.png
    - images/light blue geode.png
    - images/orange and black.png
    - images/pink geode.png
    - images/purple agate.png
    - images/purple detailed.png
    - images/royal blue.png
    - images/teal.png
    - images/yellow.png
    - images/red geode.png
    - images/gallery.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
